# Generated by Django 4.2.5 on 2023-11-06 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=90, verbose_name='login')),
                ('password', models.CharField(max_length=90, verbose_name='password')),
                ('name', models.CharField(max_length=90, verbose_name='name')),
                ('email', models.CharField(max_length=90, verbose_name='email')),
                ('phone', models.CharField(max_length=90, verbose_name='phone')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='name')),
                ('players', models.ManyToManyField(blank=True, related_name='playerTeam', to='core.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='sport',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.sport'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.ManyToManyField(blank=True, related_name='teamsMatch', to='core.team')),
                ('winner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='name')),
                ('admin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user')),
                ('bracket', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.bracket')),
                ('sport', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.sport')),
                ('teams', models.ManyToManyField(blank=True, related_name='teamsChampionship', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(blank=True, related_name='playersChallenge', to='core.player')),
                ('winner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
        migrations.AddField(
            model_name='bracket',
            name='finals',
            field=models.ManyToManyField(blank=True, related_name='finalMatch', to='core.match'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='quarterFinals',
            field=models.ManyToManyField(blank=True, related_name='quarterMatch', to='core.match'),
        ),
        migrations.AddField(
            model_name='bracket',
            name='semiFinals',
            field=models.ManyToManyField(blank=True, related_name='semiMatch', to='core.match'),
        ),
    ]
